from django.urls import path, include, re_path
from . import views
from .views import Appoint, Appointdealers, HomePageView

urlpatterns = [
    path('',views.index, name='index'),
    path('aboutus/',views.aboutus, name='aboutus'),
    path('addrt/',views.addrtoffice, name='addrt'),
    path('showrt/',views.showrtoffice,name='showrt'),
    path('editrt/<str:rcode>', views.editrtoffice,name='editrt'),
    path('updatert/<str:rcode>', views.updatertoffice, name='updatert'),
    path('deletert/<str:rcode>', views.destroyrtoffice, name='deletert'),
    path('addtax/', views.addtax, name='addtax'),
    path('showtax/', views.showtax, name='showtax'),
    path('edittax/<int:taxcode>', views.edittax, name='edittax'),
    path('updatetax/<int:taxcode>', views.updatetax, name='updatetax'),
    path('deletetax/<int:taxcode>', views.destroytax, name='deletetax'),
    path('addlic/', views.addlic, name='addlic'),
    path('showlic/', views.showlic, name='showlic'),
    path('editlic/<int:id>', views.editlic, name='editlic'),
    path('updatelic/<int:id>', views.updatelic, name='updatelic'),
    path('deletelic/<int:id>', views.destroylic, name='deletelic'),
    path('viewrto/', views.viewoffices, name='viewrto'),
    path('viewtax/', views.viewtaxrate, name='viewtax'),
    path('viewlicense/', views.viewlicenserate, name='viewlicense'),
    path('add_emp/', views.employeeregistation, name='add_emp'),
    path('printemp/', views.printemployee, name='printemp'),
    re_path(r'^appoint/(?P<adharno>[\w]+)/$', Appoint.as_view(), name='appoint'),
    path('add_dealer/', views.dealerregistation, name='add_dealer'),
    path('printdealer/', views.printdealers, name='printdealer'),
    re_path(r'^dealerappoint/(?P<dcode>[\w]+)/$',Appointdealers.as_view(), name='dealerappoint'),
    path('loginpage/', HomePageView.as_view(), name='loginpage'),
    path('search_results', views.SearchResultsView, name='search_results'),
    path('showlicrate/', views.selectlicrate, name='showlicrate'),
    path('applyleaners/<int:id>', views.displayleanersapp, name='applyleaners'),
    path('vehiclereg/', views.viewvehicletax, name='vehiclereg'),
    path('updateveh/<int:id>', views.vehcashupdation, name='updateveh'),
    path('numissue/', views.empnumissue, name='numissue'),
    path('addquest/', views.addquestion, name='addquest'),
    path('showquest/', views.showquestion, name='showquest'),
    path('editquest/<int:id>', views.editquestion, name='editquest'),
    path('updatequest/<int:id>', views.updatequestion, name='updatequest'),
    path('deletequest/<int:id>', views.destroyquestion, name='deletequest'),
    path('ltest/',views.leanersexam, name='ltest'),
    path('dtest/',views.drivingLicense, name='dtest'),
    path('driving/', views.issuedrivinglic, name='driving'),
    path('printleaner/', views.printleaners, name='printleaner'),
    path('printdriving/',views.printdriving,name='printdriving'),
    path('changepass/', views.changepassword, name='changepass'),
    path('listveh/', views.printveh, name='listveh'),
]