# Generated by Django 3.2.4 on 2021-06-13 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateField(default=datetime.date.today, verbose_name='Application Date')),
                ('aname', models.CharField(max_length=50, verbose_name='Name of the Applicant')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='Male', max_length=20, verbose_name='Gender')),
                ('fname', models.CharField(max_length=50, verbose_name="Father's Name")),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('adharno', models.CharField(max_length=20, verbose_name='Adhar No')),
                ('quali', models.CharField(max_length=50, verbose_name='Qualification')),
                ('lcode', models.IntegerField()),
                ('lname', models.CharField(max_length=50)),
                ('cardno', models.CharField(max_length=20, verbose_name='Credit Card No')),
                ('amtpaid', models.IntegerField()),
                ('testdate', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('lno', models.IntegerField(default=0)),
                ('vfrom', models.DateField()),
                ('vto', models.DateField()),
                ('status', models.CharField(default='N', max_length=50)),
                ('rcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srto.rtoffice')),
            ],
        ),
    ]
