# Generated by Django 3.2.4 on 2021-06-13 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0002_lapptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapptable',
            name='amtpaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lapptable',
            name='cardno',
            field=models.CharField(default='0', max_length=20, verbose_name='Credit Card No'),
        ),
        migrations.AlterField(
            model_name='lapptable',
            name='lcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lapptable',
            name='lname',
            field=models.CharField(default='x', max_length=50),
        ),
        migrations.AlterField(
            model_name='lapptable',
            name='vfrom',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lapptable',
            name='vto',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
