# Generated by Django 3.2.4 on 2021-06-13 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0003_auto_20210613_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapptable',
            name='testdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
