# Generated by Django 3.2.4 on 2021-06-15 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0004_alter_lapptable_testdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapptable',
            name='cardno',
            field=models.CharField(max_length=20, verbose_name='Credit Card No'),
        ),
        migrations.CreateModel(
            name='Vehicleregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdate', models.DateField(default=datetime.date.today, verbose_name='Applicantion Date')),
                ('vname', models.CharField(max_length=50, verbose_name='Vehicle Name')),
                ('eno', models.CharField(max_length=25, verbose_name='Engine No')),
                ('chno', models.CharField(max_length=25, verbose_name='Chaiss No')),
                ('ymanu', models.IntegerField(verbose_name='Year of Manufacturing')),
                ('mnamu', models.IntegerField(verbose_name='Month of Manufacturing')),
                ('taxcode', models.IntegerField(verbose_name='Tax Category')),
                ('vprice', models.IntegerField(verbose_name='Price of the Vehicle')),
                ('tax', models.IntegerField(verbose_name='Tax Amount')),
                ('cardno', models.IntegerField(verbose_name='Credit Card No')),
                ('oname', models.CharField(max_length=100, verbose_name='Vehicle Owners Name')),
                ('address', models.CharField(max_length=100, verbose_name='Owners Address')),
                ('adharno', models.CharField(max_length=20, verbose_name='Adhar No')),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('regno', models.IntegerField(default=0, verbose_name='Reg. No')),
                ('vfrom', models.DateField(default=datetime.date.today)),
                ('vto', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='N', max_length=10)),
                ('dcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srto.dealers')),
                ('rcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srto.rtoffice')),
            ],
        ),
    ]
