# Generated by Django 3.2.4 on 2021-06-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0005_auto_20210615_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregister',
            name='cardno',
            field=models.CharField(max_length=20, verbose_name='Credit Card No'),
        ),
    ]
