# Generated by Django 3.2.4 on 2021-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0006_alter_vehicleregister_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregister',
            name='dcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='rcode',
            field=models.CharField(max_length=50),
        ),
    ]
