# Generated by Django 3.2.4 on 2021-06-16 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0007_auto_20210615_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(verbose_name='Question No')),
                ('qname', models.CharField(max_length=250, verbose_name='Question')),
                ('op1', models.CharField(max_length=100, verbose_name='Option 1')),
                ('op2', models.CharField(max_length=100, verbose_name='Option 2')),
                ('op3', models.CharField(max_length=100, verbose_name='Option 3')),
                ('op4', models.CharField(max_length=100, verbose_name='Option 4')),
                ('ans', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', verbose_name='Answer Option')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='appdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Application Date'),
        ),
    ]
