# Generated by Django 3.2.4 on 2021-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0008_auto_20210616_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='Answer Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='op1',
            field=models.CharField(max_length=250, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='op2',
            field=models.CharField(max_length=250, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='op3',
            field=models.CharField(max_length=250, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='op4',
            field=models.CharField(max_length=250, verbose_name='Option 4'),
        ),
    ]
