# Generated by Django 3.2.4 on 2021-06-17 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0009_auto_20210616_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivinglicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lno', models.IntegerField(verbose_name='Licence No')),
                ('apdate', models.DateField(default=datetime.date.today, verbose_name='Application Date')),
                ('lcode', models.IntegerField()),
                ('lname', models.CharField(max_length=100)),
                ('amt', models.IntegerField()),
                ('cardno', models.CharField(max_length=20)),
                ('dlno', models.IntegerField(default=0)),
                ('ldate', models.DateField(default=datetime.date.today, verbose_name='Issue Date')),
                ('vfrom', models.DateField(default=datetime.date.today)),
                ('vto', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='N', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='lapptable',
            name='lno',
            field=models.IntegerField(default=0, verbose_name='Your License No'),
        ),
    ]
