# Generated by Django 3.2.4 on 2021-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0010_auto_20210617_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglicense',
            name='aname',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='rcode',
            field=models.CharField(default='KL-01', max_length=50),
        ),
    ]
