# Generated by Django 3.2.4 on 2021-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0011_auto_20210618_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='aname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='rcode',
            field=models.CharField(max_length=50),
        ),
    ]
