# Generated by Django 3.2.4 on 2021-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srto', '0012_auto_20210618_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapptable',
            name='email',
            field=models.EmailField(default='xxx@xx.com', max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lapptable',
            name='phone',
            field=models.CharField(default='XXX', max_length=20, verbose_name='Phone Number'),
        ),
    ]
